name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ "main" ]

jobs:
  sync-to-huggingface-spaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Hugging Face Hub
        uses: nateraw/huggingface-cli-action@v0.0.5
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_id: ${{ secrets.HF_SPACE_NAME }}
          repo_type: space